apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library
data:
  DATABASE_USERNAME: "postgres"
  JWT_EXPIRATION: "86400000"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
  SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin-service"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  SPRING_BOOT_ADMIN_CLIENT_INSTANCE_PREFER_IP: "true"

  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "bibliotecznyksiazkomat@gmail.com"
  MAIL_SMTP_AUTH: "true"
  MAIL_SMTP_STARTTLS_ENABLE: "true"
  MAIL_SMTP_STARTTLS_REQUIRED: "true"
