# Shared ConfigMap for database credentials
apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library
data:
  DATABASE_USERNAME: "postgres"
  JWT_EXPIRATION: "86400000"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"

  # Mail configuration (public settings)
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "bibliotecznyksiazkomat@gmail.com"
  MAIL_SMTP_AUTH: "true"
  MAIL_SMTP_STARTTLS_ENABLE: "true"
  MAIL_SMTP_STARTTLS_REQUIRED: "true"
