apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: library-dev-binding
  namespace: library
subjects:
  - kind: User
    name: dev
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: library-dev-role
  apiGroup: rbac.authorization.k8s.io

