apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: library-intern-binding
  namespace: library
subjects:
  - kind: User
    name: intern
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: library-intern-role
  apiGroup: rbac.authorization.k8s.io