apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: library
  name: library-dev-role
rules:
  - apiGroups: ["*", ""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: library
  name: library-intern-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["pods", "services", "deployments", "ingresses", "configmaps", "pods/log"]
    verbs: ["get", "list", "watch"]



